### ISSUE TITLE
Tag a point-release so we can do a stable install...

### ISSUE THREAD

**Issue by assertchris** [Nexmo/nexmo-laravel#1]
Even a `0.1` would be good, and still indicates the library is in a state of flux. The benefit is that early adopters can have the version they've coded against in their lock file (vs. a reference to dev-master).

**Comment by tjlytle** [comment]
Sorry, didn't see thise earlier. Will make it match the beta tagged released of the underlying client library next week. I think that'll achieve the same thing.

**Comment by tjlytle** [comment]
Added a beta release that you can reference. Going forward will release in step with `nexmo/client` until `1.0.0`.
