### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by taslimsuman** [Nexmo/nexmo-laravel#10]
Hi, I have created fresh laravel project 5.4. Im getting error when enter "composer composer require nexmo/laravel 1.0.0-beta3". I tried several times but failed. Error shows as below.

Problem 1
- Can only install one of: nexmo/client[1.0.0-beta3, 1.0.0-beta4].
-
-

**Comment by tjlytle** [comment]
@taslimsuman I should have a release in the next day or so that normalizes the pre 1.0 releases so there are no more issues.
