### ISSUE TITLE
nexmo not worked with lumen

### ISSUE THREAD

**Issue by EugeneBogun** [Nexmo/nexmo-laravel#14]
(1/1) FatalThrowableErrorCall to undefined function Nexmo\Laravel\config_path()
--
in NexmoServiceProvider.php (line 16)
at NexmoServiceProvider->boot()
at call_user_func_array(array(object(NexmoServiceProvider), 'boot'), array())in BoundMethod.php (line 29)
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php (line 87)
at BoundMethod::callBoundMethod(object(Application), array(object(NexmoServiceProvider), 'boot'), object(Closure))in BoundMethod.php (line 31)
at BoundMethod::call(object(Application), array(object(NexmoServiceProvider), 'boot'), array(), null)in Container.php (line 549)
at Container->call(array(object(NexmoServiceProvider), 'boot'))in Application.php (line 197)
at Application->register(object(NexmoServiceProvider))in app.php (line 111)
at require('/app/bootstrap/app.php')in index.php (line 14)

Lumen 5.5

**Comment by percymamedy** [comment]
Lumen has no config_path() method as all configuration are stored in ```.env```

**Comment by EugeneBogun** [comment]
@percymamedy I think this package should be changed to universal solution for laravel and lumen
