### ISSUE TITLE
Change Client\Credentials\SharedSecret to Nexmo\Client\Credentials\SignatureSecret

### ISSUE THREAD

**Issue by EugeneBogun** [Nexmo/nexmo-laravel#15]
https://github.com/Nexmo/nexmo-php/blob/685636c60c934250711777bd4eeabec6ef5106e2/CHANGELOG.md

**Comment by percymamedy** [comment]
Already changed in latest PR on master.

 https://github.com/Nexmo/nexmo-laravel/blob/master/src/NexmoServiceProvider.php#L173

Next release should reflect that change.

**Comment by mheap** [comment]
That's been released now. Thanks once again @percymamedy 

https://github.com/Nexmo/nexmo-laravel/releases/tag/1.0.1
