### ISSUE TITLE
confusing documentation

### ISSUE THREAD

**Issue by vwasteels** [Nexmo/nexmo-laravel#18]
Hello,

for Laravel 5.5, the Notification documentation says to add nexmo config in ```config/services.php```
https://laravel.com/docs/5.5/notifications#sms-notifications

not in ```config/nexmo.php```

I ran ```php artisan vendor:publish``` but still no ```config/nexmo.php```

And I receive this error : 

```
Target [Nexmo\Client\Credentials\CredentialsInterface] is not instantiable while building [Nexmo\Client].
```

any idea ?

**Comment by vwasteels** [comment]
ok my bad, ```composer install``` went wrong

**Comment by mheap** [comment]
@vwasteels Glad to hear you got it sorted. Is there anything we could do to improve the documentation around this?

**Comment by vwasteels** [comment]
No I think it's more on laravel side to add some doc around Nexmo usage. They only talk about sending SMS in Notifications, but that was not my need.

thanks for your time :)
