### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate while NEXMO API integration in Laravel

### ISSUE THREAD

**Issue by jimkaler** [Nexmo/nexmo-laravel#22]
Hello guys,
I am having error while using Nexmo sms api in laravel. i have tried everything what i found on google please help me out.

**Comment by mheap** [comment]
Hey @JimKaler,

It sounds like an environment issue to me. Does this occur when you're running the code locally, or when deployed to a server somewhere?

**Comment by jimkaler** [comment]
Hi @mheap 
I am facing this problem on local server.

**Comment by mheap** [comment]
Which operating system are you using?

**Comment by jimkaler** [comment]
Windows 10 Home 64bit

**Comment by jimkaler** [comment]
![error](https://user-images.githubusercontent.com/36437555/36148005-6ed50bb2-10e0-11e8-8f54-a9a7160d5d14.png)

**Comment by jimkaler** [comment]
This is My Controller
![controller](https://user-images.githubusercontent.com/36437555/36148042-97220142-10e0-11e8-8d76-1f04c2fef1a4.png)

**Comment by mheap** [comment]
@JimKaler Thanks for the info. It seems as though this may be a known issue with some distributions of PHP for Windows

https://github.com/nexmo/nexmo-php#troubleshooting

**Comment by jimkaler** [comment]
@mheap i have tried it already but didn't effect :(

**Comment by mheap** [comment]
@JimKaler What happens if we take the PHP client out of the picture? Can you run these two items on the command line for me? You may need to use `bash` for Windows

```bash
php -r 'file_get_contents("https://api.nexmo.com");';
```

```bash
curl -i https://api.nexmo.com
```

**Comment by jimkaler** [comment]
@mheap 
i have to run these command from which directory? and i am using bash already.

**Comment by mheap** [comment]
From any directory. They try and access the Nexmo API without using any dependencies.

You will likely need to run via https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by jimkaler** [comment]
@mheap while running 
php -r file_get_contents("https://api.nexmo.com")
Warning: file_get_contents(https://api.nexmo.com): failed to open stream: HTTP r
equest failed! HTTP/1.1 404 Not Found
 in Command line code on line 1
i am getting error

**Comment by mheap** [comment]
Are you running your Laravel app via php artisan serve, or a different server?

**Comment by jimkaler** [comment]
yes via php artisan serve

**Comment by mheap** [comment]
Could you also try the following?

```bash
php -r file_get_contents("https://rest.nexmo.com")
```
