### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by yibr** [Nexmo/nexmo-laravel#32]
when i want to make a call i got this error 
Unauthorized
even with audio call so you don't need even a local server
(https://nexmo-community.github.io/ncco-examples/first_call_talk.json)

**Comment by dragonmantank** [comment]
Hello yibr!

Normally this would mean your nexmo secret and key (or app ID and private key) are probably incorrect. I would double-check this just to be safe. Check out the [Configuration Section of the README](https://github.com/Nexmo/nexmo-laravel#configuration) for more information on configuring it.

If those values are correct, could you please provide us with the code that you are using to make the call?

**Comment by yibr** [comment]
thanks for your response
for sms it works 
i will genarate a new app and key and see if this is the problem 

the code is just like the readme 
i changed this 
"answer_url"
https://nexmo-community.github.io/ncco-examples/first_call_talk.json

**Comment by dragonmantank** [comment]
Thanks. I will see if I can replicate the issue.

**Comment by yibr** [comment]
solved 
my mistake
