### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by scriptmint** [Nexmo/nexmo-laravel#33]
Hey there, Your package doesn't support Laravel 6.0.

**Comment by dragonmantank** [comment]
Hello!

We have an upcoming change for some updates, and will make sure that this works with v6.0. 

Thanks for the heads-up!

**Comment by scriptmint** [comment]
@dragonmantank any ETA?

**Comment by dragonmantank** [comment]
"Soon"?

We are in the final stages for our `nexmo/client` 2.0.0 release (which you can follow over here: https://github.com/Nexmo/nexmo-php/pull/192). Once that PR is approved and we get a release tagged both in github and set up through our internal procedures, that will go out. Very shortly after that this package will get updated to use the new 2.0.0 version of the SDK. 

I'm hoping we will get everything cut by end of this week or early next week, but I can't give an exact date.

**Comment by MartinDinkov** [comment]
Thank you for the great package, guys! Can't wait to upgrade to 6.0. :)

**Comment by scriptmint** [comment]
Still waiting!

**Comment by afolson** [comment]
You’re just going to have to be patient with us, thanks!

**Comment by jadonbrownza** [comment]
Hey guys, thanks for the great work!

I'm also waiting for the compatibility update.

**Comment by charlielangridge** [comment]
As am I - thanks tho!

**Comment by scriptmint** [comment]
I moved to twilio now...they already have Laravel 6.0 support. You people should have done this a week ago, as Laravel 6.0 was announced a month ago.

**Comment by dragonmantank** [comment]
@ScriptMint I'm sorry to hear that. Hopefully everything works out.

@Unholny  @scheMeZa @charlielangridge I've just released [2.0.0](https://github.com/Nexmo/nexmo-laravel/releases/tag/2.0.0) which includes support for Laravel 6.0, as well as support for our new split packages if you run into Guzzle adapter incompatibilities with other libraries.

Enjoy!

**Comment by MartinDinkov** [comment]
@dragonmantank Thank you for the release! It's working perfectly!
