### ISSUE TITLE
failed on production

### ISSUE THREAD

**Issue by BSN4** [Nexmo/nexmo-laravel#36]
to reproduce this bug remove your vendor folder and try :

`composer install --prefer-dist --no-scripts --no-dev`

this issue only happens on production

Class 'Http\Adapter\Guzzle6\Client' not found

I solved it by adding guzzle adapter to dependency

**Comment by dragonmantank** [comment]
Can you supply a copy of your `composer.lock`, or failing that, the `require` section of your `composer.json`? That way we can investigate exactly what libraries are being pulled in and possibly causing a problem.

**Comment by BSN4** [comment]
```

```

**Comment by dragonmantank** [comment]
@if4lcon Can you do the following and see if this works now?

1. `composer clear-cache`
2. `rm composer.lock`
3. `composer install --prefer-dist --no-scripts --no-dev`

Clearing the cache and deleting the lock file will just make sure that the changes I made are picked up.

Let me know if there are any error or incompatibilities. I could not test the Nova or VIPS packages as I do not have access to Nova nor the VIPS extension installed.

**Comment by BSN4** [comment]
yup it works now thank you

composer dump-autoload --optimize

should be called

**Comment by dragonmantank** [comment]
Great! Sorry for the mixup with this, and glad we got it resolved fairly quickly. Let me know if you run int any other problems!
