### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by mvzmvcaof** [Nexmo/nexmo-laravel#4]
![image](https://cloud.githubusercontent.com/assets/12593869/18985891/5cb5e0f6-8724-11e6-9dde-5e070f25fb65.png)

??? error

**Comment by mvzmvcaof** [comment]
Edited done   cURL error 60

![route](https://cloud.githubusercontent.com/assets/12593869/18986654/f920199a-8727-11e6-8e09-64f7e08370f9.png)
![sms controller](https://cloud.githubusercontent.com/assets/12593869/18986656/fbd71d78-8727-11e6-9d45-89dd6104b194.png)

-why done sms 66805456789  one number   want to  sms/661234567890 done send 661234567890
Pick another number sms   OTP  verification  ??

**Comment by mohamedryan** [comment]
Go to http://curl.haxx.se/ca/cacert.pem and download the pem file and save in your php installation directory ( make sure while saving it retains the extension and not saved as a text file )

Now, open your php.ini file, scroll to the bottom and add the following line:

```
[cURL] 
curl.cainfo="C:\wamp\bin\php\curl\cacert.pem"
```

Replace C:\wamp\bin\php\curl\cacert.pem with the actual path.

restart apache and if u use a bash not VH then, close laravel serve artisan "Ctrl + c " and open it again

Courtesy: http://stackoverflow.com/questions/17478283/paypal-access-ssl-certificate-unable-to-get-local-issuer-certificate

**Comment by jimkaler** [comment]
i have done what @mohamedryan have said but still getting problem while using NEXMO in laravel
