### ISSUE TITLE
Package zendframework/zend-diactoros is abandoned

### ISSUE THREAD

**Issue by greatsami** [Nexmo/nexmo-laravel#42]
Hi 

when I installed the package on my Laravel project, I faced this message in cmd:

`Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.`

PHP: v7.2
Laravel: v6.2

**Comment by dragonmantank** [comment]
Hello!

This is from the underlying `nexmo/client` library, which have a release coming out relatively soon that will remove that message. This message is just a notification that the ZF package has changed names though, and doesn't have any impact on the actual usage of the library, so there shouldn't be any side effects.
