### ISSUE TITLE
Laravel 8 compatibility

### ISSUE THREAD

**Issue by ctschetter** [Nexmo/nexmo-laravel#47]
Laravel 8 requires Guzzle 7.0.1 but the nexmo-laravel package appears to require 6.5.

You CAN follow the configuration guide to install a custom HTTP provider besides Guzzle, but this package should natively support the newest version of Laravel.

**Comment by dragonmantank** [comment]
Hello!

This is currently on our roadmap to update. As you mention, we do technically support any PSR-18 HTTP client (either via the HTTPlug project or in cases like Guzzle 7 which are PSR-18 compatible). I'll leave this open until we get it all sorted out.

**Comment by ctschetter** [comment]
Thank you, and thank you for all your work on this package! Without this update, I can't seem to make this package and Laravel 8 play nice, even with a separate HTTP client (following the guide.)

---
Problem 1
    - Installation request for nexmo/laravel ^2.3 -> satisfiable by nexmo/laravel[2.3.0].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].

**Comment by dragonmantank** [comment]
As an update, we're updating to support Guzzle 7 out-of-the-box, so this should be resolved soon.

**Comment by ctschetter** [comment]
@dragonmantank outstanding! Thank you!

**Comment by dragonmantank** [comment]
![cc7d9b_aa62fff3564f4383b1077cc42079ccf2~mv2](https://user-images.githubusercontent.com/108948/92785444-6cc82280-f375-11ea-9e72-ff3544ef6625.jpg)

I released `nexmo/client:2.4.0` which bumps our minimum to PHP to 7.2 and uses Guzzle 7 now, so this should be compatible. At the very least it installed in my fresh install of Laravel 8. 

I'll leave this issue open for a bit until I get a concrete yes or no from a real-world application, but the underlying client release should do it.

**Comment by andriihorpenko** [comment]
This issue may be closed now. I've successfully upgraded to Guzzle 7 and tested Nexmo on Laravel 8 — works like a charm. Thanks!
