### ISSUE TITLE
Vonage Voyagers application: Create a more detailed SMS log

### ISSUE THREAD

**Issue by FPMedia** [Nexmo/nexmo-laravel#48]
I have had an issue before where I've sent an SMS which hasn't been delivered and I couldn't drill into the actual API request for the SMS with a response. I figured the issue out which was that I hadn't formatted the number correctly but this was through a more manual trial / error process.

**Comment by phazonoverload** [comment]
Hey @FPMedia - could you provide some more context please? What error was actually returned (or behaviour that made you realise that messages weren't being sent)? Anything else that might be helpful?

**Comment by FPMedia** [comment]
Thank you for the response. There wasn't an actual error / error message in the Vonage Dashboard, the SMS messages just weren't being received at the specified cell number. I wasn't sure why the message wasn't being delivered as there were no specific errors.
After investigation, I realised that the issue was that I wasn't submitting to a correctly formed mobile number. So maybe, the suggestion here is to have some way of showing whether a message was successfully delivered?

**Comment by dragonmantank** [comment]
Understood. The only way to guarantee being able to see delivery status is to set up a [Delivery Receipt Webhook](https://developer.nexmo.com/messaging/sms/guides/delivery-receipts) ([sample PHP code](https://developer.nexmo.com/messaging/sms/code-snippets/delivery-receipts/php)). Some errors are returned automatically as Exceptions in the SDK, but some errors are not able to be determined until we try and hand it off to a carrier. In those latter cases, Delivery Receipts are the only way to know.

For straight SMS there are actually quite a few things that can happen even after we hand it off to a carrier. Some more info can be found [in our troubleshooting Knowledge Base article](https://help.nexmo.com/hc/en-us/articles/204016013-Why-was-my-SMS-not-delivered-), and how Delivery Receipts work is [different for different countries](https://help.nexmo.com/hc/en-us/articles/115011781468). For example, in the US and Canada Delivery Receipts are only returned when a carrier receives the message, not when it actually hits the handset. 

With all that in mind, I don't believe that there is anything we can add to either the Laravel or the base PHP SDK to help illuminate when things go wrong, above-and-beyond setting up a webhook for the Delivery Receipt.

**Comment by FPMedia** [comment]
Hi Chris,

No stress, this is actually the perfect solution, thank you!



*Regards,*

<https://webinkdesign.co.za/>

*Disclaimer*

The information contained in this communication from the sender is
confidential. It is intended solely for use by the recipient and others
authorized to receive it. If you are not the recipient, you are hereby
notified that any disclosure, copying, distribution or taking action in
relation of the contents of this information is strictly prohibited and may
be unlawful.

**Comment by FPMedia** [comment]
Hi Chris,

No stress, this is actually the perfect solution, thank you!

**Comment by phazonoverload** [comment]
Appreciate you responding Chris, and thanks for providing some more detail @FPMedia. For the sake of the Voyagers Application I'm happy with the state of this issue and will pop you an email shortly. I think based on the convo above this issue is good to be closed 👍

**Comment by FPMedia** [comment]
Great, thanks so much Kevin.



*Regards,*

<https://webinkdesign.co.za/>

*Disclaimer*

The information contained in this communication from the sender is
confidential. It is intended solely for use by the recipient and others
authorized to receive it. If you are not the recipient, you are hereby
notified that any disclosure, copying, distribution or taking action in
relation of the contents of this information is strictly prohibited and may
be unlawful.
