### ISSUE TITLE
Migrate to Vonage/vonage-php-sdk-core before 10/01/2021

### ISSUE THREAD

**Issue by redalpha01** [Nexmo/nexmo-laravel#49]
As written in the first paragraph of the Nexmo/nexmo-php readme:

> This library and it's associated packages, nexmo/client and nexmo/client-core have transitioned into a "Maintenance Only" mode. For the next twelve (12) months, this library will only receive bug or security fixes. This library will officially be End of Life as of October 1st, 2021.
> 
> We recommend users begin migrating over to https://github.com/vonage/vonage-php-sdk-core and the vonage/client and vonage/client-core packages for their applications. The Vonage packages fully support the \Nexmo namespace and should be a drop-in replacement for the Nexmo packages.

**Comment by dragonmantank** [comment]
A formal switchover is on our roadmap, don't worry. At the moment there aren't any new product releases coming that will impact this Laravel package, and it will most likely come with a new package name, `vonage/laravel`. 

That being said, the code is designed to be backwards-proof. The `nexmo/client` and `nexmo/client-core` packages are actually the same code as `vonage/client` and `vonage/client-core` and allow you to use both namespaces at the same time. If your `composer.lock` shows `nexmo/client-core` 2.3 or greater, you're already using the new Vonage code, the Facade is just still pointing at Nexmo. We'll make sure this package is supported as long as possible under the same ideas.

**Comment by SecondeJK** [comment]
This package is officially abandoned in favour of https://github.com/Vonage/vonage-laravel. Please use that, and open tickets in that repo if required, thanks.
