### ISSUE TITLE
message is garbled

### ISSUE THREAD

**Issue by ha-family** [Nexmo/nexmo-laravel#5]
hi,
i have an issue while i was sending message
i've got garbled message in chinese, how to set nexmo message type to unicode???

thank you

**Comment by tjlytle** [comment]
You'll need to set the `type` to `unicode` for now. See this thread: https://github.com/Nexmo/nexmo-php/issues/8

**Comment by ha-family** [comment]
thanks for your reply,
but i use Notifications in Laravel, 
the way i was used is follow the document like below
and i don't know how to add type => 'unicode' into it...
could you help me? 
 thanks.

>     public function toNexmo($notifiable)
>     {
>             return (new NexmoMessage)->content('Chinese Message here.....');
>     }

**Comment by tjlytle** [comment]
@liu-yuhuan Sorry for letting this drop. You'd have to create another unicode delivery channel. However, the related issue references code that autodetects and selects unicode if needed. I may update the library with that support, then it would out of the box.

**Comment by isaacesso** [comment]
@liu-yuhuan here is how to set unicode type with laravel notifications:
```
public function toNexmo($notifiable)
{
    return (new NexmoMessage)->unicode()->content('Chinese Message here.....');
}
```

**Comment by mheap** [comment]
Thanks for the assist @isaacesso
