### ISSUE TITLE
nexmo/client 0.4.0 error

### ISSUE THREAD

**Issue by AbingPj** [Nexmo/nexmo-laravel#53]
After Composer Update,.. 

`Problem 1
   - nexmo/laravel 0.4.0 requires nexmo/client 0.4.0 -> satisfiable by nexmo/client[0.4.0].
   - nexmo/laravel 0.4.0 requires nexmo/client 0.4.0 -> satisfiable by nexmo/client[0.4.0].
   - Conclusion: remove nexmo/client 0.4.0
   - Installation request for nexmo/laravel ^0.4.0 -> satisfiable by nexmo/laravel[0.4.0].`

Any idea how to solve of this? we are using laravel 5.7

**Comment by dragonmantank** [comment]
Unfortunately 0.4.0 is over 3 years old and is unsupported.

I would try updating `nexmo/laravel` to `^2.0` and see if that works first. I _think_ it should still work fine with Laravel 5.7.

**Comment by AbingPj** [comment]
> Unfortunately 0.4.0 is over 3 years old and is unsupported.
> 
> I would try updating `nexmo/laravel` to `^2.0` and see if that works first. I _think_ it should still work fine with Laravel 5.7.

what should we do?  I`m just the new developer of the project, It was pass to me. I don`t know how they set it.
Should I Update the code? or only the version?

By the way, thanks for your response.

**Comment by dragonmantank** [comment]
The easiest thing to try is just upgrade our package and see how that goes:

`composer require -W nexmo/laravel:^2.0`

That will upgrade our package and any dependencies that we require. You will then need to test your application to make sure that everything still functions as you intend. The upgrade may require internal changes to your applications code as there have been quite a few changes between your installed version and the newer versions of our SDK. Anywhere our code is referenced you'll want to test and see if anything fails, and fix accordingly. 

If the composer command fails or has any other incompatibilities, you'll need to do the same and upgrade any other blockers. Worst case you can look into something like https://laravelshift.com/ which can help update your Laravel version and underlying dependencies (Laravel Shift has no affiliation with Vonage or this package, I just know they do good work on this front). 

Hope that helps! If you can get upgraded and run into any other issues, feel free to open a new issue.
