### ISSUE TITLE
Missing ability to search landline-toll-free 

### ISSUE THREAD

**Issue by christineRidown** [Nexmo/nexmo-laravel#62]
You are unable to search for type landline-toll-free as the protected parameter is missing from the file.
## Expected Behavior
Availability search for toll free numbers

## Current Behavior
When running a search for toll free numbers the following error is produced:

InvalidArgumentException: Invalid type of number in file /vendor/vonage/client-core/src/Numbers/Filter/AvailableNumbers.php on line 219

#0 //vendor/vonage/client-core/src/Numbers/Filter/AvailableNumbers.php(86): Vonage\Numbers\Filter\AvailableNumbers-&gt;setType('landline-toll-f...')
#1 /vendor/vonage/client-core/src/Numbers/Client.php(236): Vonage\Numbers\Filter\AvailableNumbers-&gt;__construct(Array)

When looking in the Filter file I noticed that only mobile-lvn and landline are accepted types to search by.  

## Steps to Reproduce (for bugs)

1. set type to 'landline-toll-free'
2.
3.
4.

## Your Environment

* Version used: "nexmo/laravel" 2.4.1
* Environment name and version (e.g. PHP 7.2 on nginx 1.19.1): PHP 7.4|8
* Operating System and version:

**Comment by dragonmantank** [comment]
There was a reason we did not do `landline-toll-free`, let me see if I can track down why we did that. If we don't have a good reason anymore I'll get this fixed!

**Comment by christineRidown** [comment]
That would be brilliant.  I have just added it to test and it now works.  But obviously I don't want to mod the files! ;)  I'd be interested to know why you would have stopped it as well, as I have used your package for a long time now, and it used to work fine. I hope it can be added back as we have clients who would like to use the facility

**Comment by dragonmantank** [comment]
Totally understand! I feel like there used to be address restrictions on toll free numbers and the API always returned an error, so we started checking for it to avoid an HTTP request in v2. It's not blowing up in the API, so I just want to check that there wasn't another reason.

**Comment by christineRidown** [comment]
Ah yes, I work with Norway numbers which have address restrictions as well for landline but we have bypassed it by making sure if that is selected they are taken to a form where we have to manually request/process them.  The joys.  Thanks for looking into this so quickly as well.  Greatly appreciated

**Comment by dragonmantank** [comment]
This should be fixed with the 2.9.0 release of `vonage/client-core`. Let me know if it gives you any trouble!

**Comment by christineRidown** [comment]
Thanks, I have tried to update my composer file to 2.9 but I am getting the following message:  Root composer.json requires vonage/client ^2.9.0, found vonage/client[2.x-dev] but it does not match your minimum-stability

Am I missing something, as I can see in the github repository that its available.

**Comment by dragonmantank** [comment]
`vonage/client` is a wrapper package, with the actual code living in `vonage/client-core`. 

Try using `composer require --update-with-all-dependencies nexmo/laravel:^2.4`

**Comment by christineRidown** [comment]
Thanks for the tip, I had to remove and re-install the package so its all working great now. :)
