### ISSUE TITLE
Error while checking PIN

### ISSUE THREAD

**Issue by BuyOwnEx** [Nexmo/nexmo-laravel#64]
Try your Verify API, but get error while checking PIN
![check](https://user-images.githubusercontent.com/44369333/127402729-6c644e97-eddb-4c44-a749-2b49785d8831.png)

**Comment by SecondeJK** [comment]
This package is officially abandoned in favour of https://github.com/Vonage/vonage-laravel. Please use that, and open tickets in that repo if required, thanks.
