### ISSUE TITLE
Larastan warnings

### ISSUE THREAD

**Issue by DanielMalmgren** [Nexmo/nexmo-laravel#65]
I'm analyzing my project with Larastan (https://github.com/nunomaduro/larastan) and it's complaining about my Nexmo code. Not sure if this is an error within nexmo-laravel or within the Larastan check.

The warning is "Call to an undefined static method Nexmo\Laravel\Facade\Nexmo::message()", which seems quite right to me, since I can't find any message() method in that facade. However, my code (pasted below) using that same method works fine, I get the feeling my php knowledge is too limited to understand why.

My simple code:
`            Nexmo::message()->send([
                'to'   => $number,
                'from' => $sender,
                'text' => $message
            ]);
`

So, the code works, but the test of it fails. Is there any more meta information that's needed in the facade for it to pass?

## Your Environment

* Version used: 2.4.1
* Environment name and version (e.g. PHP 7.2 on nginx 1.19.1): PHP 7.4.18, Laravel v8.63.0, Larastan v0.7.12
* Operating System and version: Ubuntu 20.04.2 LTS

**Comment by SecondeJK** [comment]
This package is officially abandoned in favour of https://github.com/Vonage/vonage-laravel. Please use that, and open tickets in that repo if required, thanks.
