### ISSUE TITLE
Support Laravel 9

### ISSUE THREAD

**Issue by gpcodex** [Nexmo/nexmo-laravel#69]
update please
```
"illuminate/support": "^5.2|^6.0|^7.0|^8.0",
"illuminate/support": "^5.2|^6.0|^7.0|^8.0|^9.0",
```

**Comment by cwarne** [comment]
I second this, unable to install with Laravel 9 with Laravel Spark without `illuminate/support ^9.0`

**Comment by HanifullahJamalzai** [comment]
Unable to install with laravel 9, any Solution?
Problem 1 : 
- nexmo/laravel[2.0.0, ..., 2.3.0] require php ^5.6|^7.1 -> your php version (8.1.2) does not satisfy that requirement.

**Comment by Robinvm** [comment]
I have this issue too, please fix!

**Comment by jonathan-bird** [comment]
@NexmoDev This is a blocker in many people's projects, is this a priority?

**Comment by colivinggit** [comment]
Please help us upgrade to Laravel 9.

**Comment by colivinggit** [comment]
Please update.

**Comment by gpcodex** [comment]
FYI nexmo became vonage
https://laravel.com/docs/9.x/notifications#sms-prerequisites

**Comment by SecondeJK** [comment]
This package is officially abandoned in favour of https://github.com/Vonage/vonage-laravel. Please use that, and open tickets in that repo if required, thanks.
