### ISSUE TITLE
Send SMS for two different phone numbers

### ISSUE THREAD

**Issue by dcbndev** [Nexmo/nexmo-laravel#70]
A have a booking model, which collects client phone address and has an assigned thru foreign key employee id, that has it's own phone number. When a booking is created, an observer triggers 2 notifications. With the first notification, I am sending an SMS to client, and with the second I want to inform the employee about received booking thru SMS.
How do I send notifications for two different phone numbers from the same booking model? Any help is appreciated!

`    public function routeNotificationForNexmo()
    {
        return [$this->client_phone, $this->employee->phone];
    }`

## Your Environment
* Version used: Laravel 8

**Comment by SecondeJK** [comment]
This package is officially abandoned in favour of https://github.com/Vonage/vonage-laravel. Please use that, and open tickets in that repo if required, thanks.
