### ISSUE TITLE
Support Laravel 9

### ISSUE THREAD

**Issue by colivinggit** [Nexmo/nexmo-laravel#73]

**Comment by gpcodex** [comment]
go in https://github.com/laravel/vonage-notification-channel

**Comment by Petr-Kubista** [comment]
It would be great if this change was mentioned in the Readme.

**Comment by divdax** [comment]
Any news here?

**Comment by Petr-Kubista** [comment]
@divdax previous comment mentioned it and was edited: you should use `laravel/vonage-notification-channel` for Laravel 9, as per official documentation: https://laravel.com/docs/9.x/notifications

**Comment by SecondeJK** [comment]
This package is officially abandoned in favour of https://github.com/Vonage/vonage-laravel. Please use that, and open tickets in that repo if required, thanks.
